# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Build settings
markdown: kramdown
permalink: none

# Multi Language
gems: ['jekyll-paginate', 'jekyll-sass-converter']

sass:
    sass_dir: _sass
    style: compressed

#encoding: 'GB2312'
